<?php

namespace Robotics\Providers;

use Illuminate\Support\Facades\Schema;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        //
        // Laravel uses the utf8mb4 character set by default,
        // which includes support for storing "emojis" in the database.
        // If you are running a version of MySQL older than the 5.7.7 release
        // or MariaDB older than the 10.2.2 release, you may need to manually
        // configure the default string length generated by migrations in order
        // for MySQL to create indexes for them. You may configure this by calling the
        // Schema::defaultStringLength method within your AppServiceProvider:
        Schema::defaultStringLength(191);
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}
